<div class="col-xs-12">
    <?php echo $this->getContent(); ?>
</div>
<?php echo $this->tag->form('') ?>
        <div class="col-xs-12 no-padding">
            <div class="nav-tabs-custom">
                <ul class="nav nav-tabs" role="tablist" id="container_tabs">
                    <li role="presentation" class="active"><a href="#topic" data-controls="book" role="tab" data-toggle="tab"><span class="fa fa-briefcase"></span> Topic Information</a></li>
                    <li role="presentation" ><a href="#books" data-controls="books" data-toggle="tab" role="tab"><i class="fa fa-book"></i> Books <i class="fa fa-sort-numeric-asc"></i></a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="topic">
                        <div class="row">
                            <div class="box box-primary">
                                <div class="box-header">
                                    <h3 class="box-title">Edit Topic</h3>
                                </div>
                                <div class="box-body">
                                    <div class="row">
                                        <div class="col-xs-9 no-padding">
                                            <div class="form-group-sm col-md-6 col-sm-12">
                                                <label for="name">Name</label>
                                                <?php echo $this->tag->textField(array("name", "size" => 30, 'class' => 'form-control')) ?>
                                            </div>
                                            <div class="form-group-sm col-md-6 col-sm-12">
                                                <label for="name">Active</label>
                                                <?php echo $this->tag->selectStatic(array("status", 'class' => 'form-control'), array("1" => 'YES', "0" => 'NO')) ?>
                                            </div>
                                            <div class="form-group col-sm-12">
                                                <label for="description">Description</label>
                                                <?php echo $this->tag->textArea(array("description","rows" => 10, 'class' => 'form-control')) ?>
                                            </div>
                                        </div>
                                        <div class="col-xs-3">
                                            <div class="row">
                                                <div class="form-group-sm col-sm-12">
                                                    <label for="image">Image</label>
                                                    <div class="col-xs-12 no-padding" style="margin-bottom:10px;padding-left:0;">
                                                        <img src="<?php echo $category->image ?>" class="img-responsive img-rounded img-thumbnail" id="image_thumb">
                                                    </div>
                                                    <div class="input-group input-group-sm col-xs-12">
                                                        <?php echo $this->tag->textField(array("image", "size" => 30, 'class' => 'form-control')) ?>
                                                        <span class="input-group-btn">
                                                            <button class="btn btn-default btn-flat" type="button" onclick="getImage('image','image_thumb');"><i class="fa fa-upload"></i></button>
                                                        </span>
                                                    </div>
                                                </div>

                                                <div class="form-group-sm col-sm-12">
                                                    <label for="image">Number Book Display</label>
                                                    <div class="input-group input-group-sm col-xs-12">
                                                        <?php echo $this->tag->textField(array("number_book_display", "size" => 30, 'class' => 'form-control')) ?>
                                                        <span class="input-group-addon">
                                                        <i class="fa fa-list-ol"></i>
                                                    </span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <?php echo $this->tag->hiddenField("id") ?>
                                <div class="box-footer text-right">
                                    <div class="btn-group-xs">
                                        <?php echo $this->tag->linkTo(array("category", "Cancel", "class"=>"btn btn-small btn-primary")); ?>
                                        <?php echo $this->tag->submitButton(array("Save","class"=>"btn btn-small btn-warning")) ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane" id="books">
                        <table class="table table-hover" id="sortable">
                            <?php foreach($category->ebooks as $ebook): ?>
                                <tr style="cursor: move;" data-order="<?php echo $ebook['order'] ?>" data-id="<?php echo $ebook['id'] ?>" data-name="<?php echo $ebook['name'] ?>">
                                    <td class="small-col column"><i class="fa fa-arrows-v"></i> </td>
                                    <td><?php echo $ebook['name'] ?></td>
                                    <td class="small-col text-right"><?php echo $ebook['order'] ?></td>
                                </tr>
                            <?php endforeach; ?>
                        </table>
                        <div class="box-footer text-right">
                            <div class="btn-group-xs">
                                <button class="btn btn-small btn-warning disabled" id="save_order" type="button" onclick="saveOrder(this,'<?php echo trim($category->_id) ?>');">Save Order</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script type="text/javascript">
    var description = CKEDITOR.replace( 'description' );
    CKFinder.setupCKEditor( description, '/js/ckfinder/' );
    var elmInput = '', elmViewThumb = '';
    var ebooks = new Array();
    function getImage(elementInput, elementViewthumb) {
        elmInput = elementInput;
        elmViewThumb = elementViewthumb;
        var finder = new CKFinder();
        finder.selectActionFunction = setImageField;
        finder.popup();
    }

    // This is a sample function which is called when a file is selected in CKFinder.
    function setImageField( fileUrl ) {
        document.getElementById(elmInput).value = fileUrl;
        document.getElementById(elmViewThumb).src = fileUrl;
    }
    $(function(){
        $( "#sortable tbody" ).sortable({
            placeholder: "ui-state-highlight",
            axis: 'y',
            update: function (event, ui) {
                ebooks = $.map($(this).find('tr'),function(obj, index) {
                    return {
                        id: $(obj).data('id'),
                        name: $(obj).data('name'),
                        order: (index + 1)
                    };
                });
                $('#save_order').removeClass('disabled');
            }
        }).disableSelection();
    });
    function saveOrder(myself, category_id) {
        $.ajax({
            type: "POST",
            url: "/category/saveorder",
            data: {ebooks:ebooks,id:category_id},
            beforeSend: function () {
                //$(myself).button('loading');
            },
            success: function (results) {
                $('#save_order').addClass('disabled');
                alertify.success("Saved successfully.");
            },
            error: function () {
                $('#save_order').addClass('disabled');
                alertify.error("Error: Save failed");
            }
        });
    }
</script>
<style>
    .ui-sortable-helper {
        background: #f2f2f2;
        border-top: 1px solid #dddddd;
        border-bottom: 1px solid #dddddd;
    }
    .table>tbody>tr.ui-sortable-helper>td {
        border: 0;
    }
    .ui-state-highlight {
        background: #fefbed;
    }
</style>
