<?php echo $this->getContent() ?>
<div class="col-xs-12">
    <div class="page-header">
        <div class="text-left col-xs-4 no-padding">
            <form method="get">
                <div class="input-group input-group-sm">
                    <input type="text" class="form-control" id="txt_search" name="search" value="<?php echo $search ?>">
                    <span class="input-group-btn">
                        <button id="btn_search" class="btn btn-primary btn-flat" type="submit">Search</button>
                    </span>
                </div>
            </form>
        </div>
        <div class="text-right">
            <div class="btn-group-sm">
                <?php echo $this->tag->linkTo(array("category/new", "<i class='fa fa-plus-circle'></i> | Create Topic", "class"=>"btn btn-small btn-primary")); ?>
            </div>
        </div>
    </div>
    <table class="table table-striped table-bordered table-responsive table-hover" align="center">
        <thead>
        <tr>
            <th  class="text-center small-col">#</th>
            <th  class="text-left" width="25%">Name</th>
            <th  class="text-left">Description</th>
            <th  class="text-center" width="5%">Image</th>
            <th  class="text-center" width="5%">Active</th>
            <th  class="text-center" width="10%">Created</th>
            <th  class="text-center" style="width:145px;">Action</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($pager as $index => $category) { ?>
            <?php
            if($category->status) {
                $linkLock = '<label onclick="return activeAccount(this,\''.$category->_id->{'$id'}.'\','.$category->status.');" class="label label-success"><i class="fa fa-unlock"></i></label>';
            } else {
                $linkLock = '<label onclick="return activeAccount(this,\''.$category->_id->{'$id'}.'\','.$category->status.');" class="label label-danger"><i class="fa fa-lock"></i></label>';
            }
            ?>
            <tr>
                <td><?php echo $index+1 ?></td>
                <td><?php echo $category->name ?></td>
                <td><?php echo Helper::limitString($category->description, 100) ?></td>
                <td class="text-center"><img  style="width:50px" class="img-responsive img-rounded img-thumbnail" src="<?php echo $category->image ?>"/></td>
                <td class="text-center"><?php echo $linkLock ?></td>
                <td class="text-center"><?php echo Helper::formatDate($category->created_at) ?></td>
                <td style="text-align: right">
                    <div class="btn-group-xs">
                        <?php echo $this->tag->linkTo(array("category/edit/" . $category->_id->{'$id'}, 'Edit | <span class="fa fa-edit"></span>', 'class' => 'btn btn-small btn-sm btn-warning')); ?>
                        <?php echo $this->tag->linkTo(array("category/delete/" . $category->_id->{'$id'}, 'Delete | <span class="fa fa-trash-o"></span>', 'class' => 'btn btn-small btn-sm btn-danger')); ?>
                    </div>
                </td>
            </tr>
        <?php } ?>
    </table>
    <div class="dataTables_paginate paging_bootstrap">
        <?php echo $pager->getLayout() ?>
    </div>
</div>
<script>
    function activeAccount(myself,id,value) {
        $.ajax({
            type:"POST",
            url:"category/active",
            data:{id:id,value:value},
            beforeSend: function() {
                $(myself).button('loading');
            },
            success:function(results) {
                $(myself).button('reset');
            },
            error:function() {
                $(myself).button('reset');
                alert("FEHLER!");
            }
        });
    }
</script>