<?php echo $this->getContent() ?>
<div class="col-xs-12">
    <div class="page-header">
        <div class="text-left col-xs-4 no-padding">
            <form method="get">
                <div class="input-group input-group-sm">
                    <input type="text" class="form-control" id="txt_search" name="search" value="<?php echo $search ?>">
                    <span class="input-group-btn">
                        <button id="btn_search" class="btn btn-primary btn-flat" type="submit">Search</button>
                    </span>
                </div>
            </form>
        </div>
        <div class="text-right">
            <div class="btn-group-sm">
                <?php echo $this->tag->linkTo(array("users/new", "<i class='fa fa-plus-circle'></i> | Create", "class"=>"btn btn-small btn-primary")); ?>
            </div>
        </div>
    </div>
    <table class="table table-striped table-bordered table-responsive table-hover" align="center">
        <thead>
        <tr>
            <th  class="text-center small-col">#</th>
            <th  class="text-left">Name</th>
            <th  class="text-left">Email</th>
            <th  class="text-right" width="10%">Phone</th>
            <th  class="text-center" width="5%">Avatar</th>
            <th  class="text-center" width="5%">Active</th>
            <th  class="text-center" width="10%">Created</th>
            <th  class="text-center" style="width:145px;">Action</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($pager as $index => $user) { ?>
            <?php
            if($user->active) {
                $linkLock = '<label onclick="return activeAccount(this,\''.$user->_id->{'$id'}.'\','.$user->active.');" class="label label-success"><i class="fa fa-unlock"></i></label>';
            } else {
                $linkLock = '<label onclick="return activeAccount(this,\''.$user->_id->{'$id'}.'\','.$user->active.');" class="label label-danger"><i class="fa fa-lock"></i></label>';
            }
            ?>
            <tr>
                <td><?php echo $index+1 ?></td>
                <td><?php echo $user->name ?></td>
                <td><?php echo $user->email ?></td>
                <td class="text-right"><?php echo $user->phone ?></td>
                <td class="text-center"><img  style="width:50px" class="img-responsive img-rounded img-thumbnail" src="<?php echo $user->avatar ?>"/></td>
                <td class="text-center"><?php echo $linkLock ?></td>
                <td class="text-center"><?php echo $user->created_at ?></td>
                <td style="text-align: right">
                    <div class="btn-group-xs">
                        <?php echo $this->tag->linkTo(array("users/edit/" . $user->_id->{'$id'}, 'Edit | <span class="fa fa-edit"></span>', 'class' => 'btn btn-small btn-sm btn-warning')); ?>
                        <?php echo $this->tag->linkTo(array("users/delete/" . $user->_id->{'$id'}, 'Delete | <span class="fa fa-trash-o"></span>', 'class' => 'btn btn-small btn-sm btn-danger')); ?>
                    </div>
                </td>
            </tr>
        <?php } ?>
    </table>
    <!--div class="dataTables_paginate paging_bootstrap">
        <ul class="pagination pagination-sm no-margin pull-right">
            <li class=""><?php echo $this->tag->linkTo("users/index", "First") ?></li>
            <li class="prev"><?php echo $this->tag->linkTo("users/index?page=" . $page->before, "Previous") ?></li>
            <li class="active"><a href="#"><?php echo $page->current, "/", $page->total_pages ?></a></li>
            <li class="next"><?php echo $this->tag->linkTo("users/index?page=" . $page->next, "Next") ?></li>
            <li class=""><?php echo $this->tag->linkTo("users/index?page=" . $page->last, "Last") ?></li>
        </ul>
    </div-->
    <div class="dataTables_paginate paging_bootstrap">
        <?php echo $pager->getLayout() ?>
    </div>
</div>
<script>
    function activeAccount(myself,id,value) {
        $.ajax({
            type:"POST",
            url:"users/active",
            data:{id:id,value:value},
            beforeSend: function() {
                $(myself).button('loading');
            },
            success:function(results) {
                $(myself).button('reset');
            },
            error:function() {
                $(myself).button('reset');
                alert("FEHLER!");
            }
        });
    }
</script>