<?php use Phalcon\Tag; ?>
<?php echo $this->getContent(); ?>
<div class="col-xs-12">
    <div class="page-header text-right">
        <div class="btn-group-xs">
            <?php echo $this->tag->linkTo(array("users/index", "Go Back", "class"=>"btn btn-small btn-primary")); ?>
            <?php echo $this->tag->linkTo(array("users/new", "<i class='fa fa-plus-circle'></i> | Create", "class"=>"btn btn-small btn-primary")); ?>
        </div>
    </div>
    <table class="table table-striped table-bordered table-responsive table-hover" align="center">
        <thead>
            <tr>
                <th  class="text-center">Id</th>
                <th  class="text-center">Name</th>
                <th  class="text-center">Email</th>
                <th  class="text-center">Avatar</th>
                <th  class="text-center">Device Of Token</th>
                <th  class="text-center">Access Of Token</th>
                <th  class="text-center">Remember Of Token</th>
                <th  class="text-center">Active</th>
                <th  class="text-center">Updated</th>
                <th  class="text-center">Created</th>
                <th  class="text-center" style="width: 13%;">Action</th>
             </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $user) { ?>
            <?php
                if($user->active) {
                    $linkLock = '<label onclick="return activeAccount(this,'.$user->id.','.$user->active.');" class="label label-success"><i class="fa fa-unlock"></i></label>';
                } else {
                    $linkLock = '<label onclick="return activeAccount(this,'.$user->id.','.$user->active.');" class="label label-danger"><i class="fa fa-lock"></i></label>';
                }
            ?>
            <tr>
                <td><?php echo $user->id ?></td>
                <td><?php echo $user->name ?></td>
                <td><?php echo $user->email ?></td>
                <td><?php echo $user->avatar ?></td>
                <td><?php echo $user->device_token ?></td>
                <td><?php echo $user->access_token ?></td>
                <td><?php echo $user->remember_token ?></td>
                <td class="text-center"><?php echo $linkLock ?></td>
                <td class="text-center"><?php echo $user->updated_at ?></td>
                <td class="text-center"><?php echo $user->created_at ?></td>
                <td style="text-align: right">
                    <div class="btn-group-xs">
                        <?php echo $this->tag->linkTo(array("users/edit/" . $user->id, 'Edit | <span class="fa fa-edit"></span>', 'class' => 'btn btn-small btn-sm btn-warning')); ?>
                        <?php echo $this->tag->linkTo(array("users/delete/" . $user->id, 'Delete | <span class="fa fa-trash-o"></span>', 'class' => 'btn btn-small btn-sm btn-danger')); ?>
                    </div>
                </td>
            </tr>
        <?php } ?>
    </table>
    <div class="dataTables_paginate paging_bootstrap">
        <ul class="pagination pagination-sm no-margin pull-right">
            <li class=""><?php echo $this->tag->linkTo("users/search", "First") ?></li>
            <li class="prev"><?php echo $this->tag->linkTo("users/search?page=" . $page->before, "Previous") ?></li>
            <li class="active"><a href="#"><?php echo $page->current, "/", $page->total_pages ?></a></li>
            <li class="next"><?php echo $this->tag->linkTo("users/search?page=" . $page->next, "Next") ?></li>
            <li class=""><?php echo $this->tag->linkTo("users/search?page=" . $page->last, "Last") ?></li>
        </ul>
    </div>
</div>
<script>
    function activeAccount(myself,id,value) {
        $.ajax({
            type:"POST",
            url:"users/active",
            data:{id:id,value:value},
            beforeSend: function() {
                $(myself).button('loading');
            },
            success:function(results) {
                $(myself).button('reset');
            },
            error:function() {
                $(myself).button('reset');
                alert("FEHLER!");
            }
        });
    }
</script>