<?php echo $this->getContent() ?>
<div class="col-xs-12 no-padding">
    <div class="page-header text-right">
        <div class="btn-group-xs">
            <?php echo $this->tag->linkTo(array("roles/new", "<i class='fa fa-plus-circle'></i> | Create", "class"=>"btn btn-small btn-primary")); ?>
        </div>
    </div>
    <table class="table table-striped table-bordered table-responsive table-hover" align="center">
        <thead>
        <tr>
            <th class="text-center small-col">#</th>
            <th class="text-left">Name</th>
            <th class="text-center small-col">Active</th>
            <th class="text-center" style="width:145px;">Action</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $index => $role) { ?>
            <?php
            if($role->active) {
                $linkLock = '<label onclick="return activeAccount(this,\''.$role->_id->{'$id'}.'\','.$role->active.');" class="label label-success"><i class="fa fa-unlock"></i></label>';
            } else {
                $linkLock = '<label onclick="return activeAccount(this,\''.$role->_id->{'$id'}.'\','.$role->active.');" class="label label-danger"><i class="fa fa-lock"></i></label>';
            }
            ?>
            <tr>
                <td><?php echo $index+1 ?></td>
                <td class="text-left"><?php echo $role->name ?></td>
                <td class="text-center"><?php echo $linkLock ?></td>
                <td class="text-center">
                    <div class="btn-group-xs">
                        <?php echo $this->tag->linkTo(array("roles/edit/" . $role->_id->{'$id'}, 'Edit | <span class="fa fa-edit"></span>', 'class' => 'btn btn-small btn-sm btn-warning')); ?>
                        <?php echo $this->tag->linkTo(array("roles/delete/" . $role->_id->{'$id'}, 'Delete | <span class="fa fa-trash-o"></span>', 'class' => 'btn btn-small btn-sm btn-danger')); ?>
                    </div>
                </td>
            </tr>
        <?php } ?>
    </table>
    <div class="dataTables_paginate paging_bootstrap">
        <ul class="pagination pagination-sm no-margin pull-right">
            <li class=""><?php echo $this->tag->linkTo("roles/index", "First") ?></li>
            <li class="prev"><?php echo $this->tag->linkTo("roles/index?page=" . $page->before, "Previous") ?></li>
            <li class="active"><a href="#"><?php echo $page->current, "/", $page->total_pages ?></a></li>
            <li class="next"><?php echo $this->tag->linkTo("roles/index?page=" . $page->next, "Next") ?></li>
            <li class=""><?php echo $this->tag->linkTo("roles/index?page=" . $page->last, "Last") ?></li>
        </ul>
    </div>
</div>
<script>
    function activeAccount(myself,id,value) {
        $.ajax({
            type:"POST",
            url:"roles/active",
            data:{id:id,value:value},
            beforeSend: function() {
                $(myself).button('loading');
            },
            success:function(results) {
                $(myself).button('reset');
            },
            error:function() {
                $(myself).button('reset');
                alert("FEHLER!");
            }
        });
    }
</script>