<div class="col-xs-12">
    <?php echo $this->getContent(); ?>
</div>
<?php echo $this->tag->form("roles/create") ?>
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title">Create Role</h3>
            </div>
            <div class="box-body">
                <div class="row">
                    <div class="form-group-sm col-md-6 col-sm-12">
                        <label for="name">Name</label>
                        <?php echo $this->tag->textField(array("name", "size" => 30, 'class' => 'form-control')) ?>
                    </div>
                    <div class="form-group-sm col-md-6 col-sm-12">
                        <label for="name">Active</label>
                        <?php echo $this->tag->selectStatic(array("active", 'class' => 'form-control'), array("1" => 'YES', "0" => 'NO')) ?>
                    </div>
                </div>
            </div>
            <?php echo $this->tag->hiddenField("id") ?>
            <div class="box-footer text-right">
                <div class="btn-group-xs">
                    <?php echo $this->tag->linkTo(array("roles", "Cancel", "class"=>"btn btn-small btn-primary")); ?>
                    <?php echo $this->tag->submitButton(array("Save","class"=>"btn btn-small btn-warning")) ?>
                </div>
            </div>
        </div>
    </div>
</form>
